import type { Directive } from "@/editor-source/directives";

/*
  РАЗМЕТКА МОДУЛЯ M1, ПЕРЕНЕСЁННАЯ ИЗ ДАННЫХ В КОД.

  Записи снимались с нашего стенда 11 августа 2026: на боевом их не было,
  и клиент видел эти страницы голым текстом. Устройство разрыва описано в
  шапке index.ts этой папки.

  Записей здесь: 3.
*/
export const markupM1: Directive[] = [
  {"id": "ebbbfbcb-0b64-4120-bee6-83d0c9c27434", "module": "m1", "blocks": [{"id": "/source/m1::chto-govoryat-lyudi-s-invalidnostyu-i-nko::paragraph::11il4cb", "kind": "paragraph", "snippet": "**Сергей Исаев, инженер по тестированию доступности интерфейсов в Яндексе**"}, {"id": "/source/m1::chto-govoryat-lyudi-s-invalidnostyu-i-nko::paragraph::c4oqbc", "kind": "quote", "snippet": "*В компании «Уфанет» я проработал девять лет. Изначально их CRM была неудобна для слабовид…"}], "target": "Quote", "targetLabel": "Quote — Сергей Исаев", "modifiers": {}, "comment": "Прямая речь Сергея Исаева — в карточку цитаты.\nПочему: Сейчас авторство стоит отдельной жирной строкой, а речь под ней — обычной врезкой. На соседних страницах такие же голоса собраны карточкой цитаты, с портретом и логотипом организации.", "status": "applied", "createdAt": "2026-08-07T09:24:02.582Z", "origin": "claude"},
  {"id": "47528755-0c1f-4a43-8174-5509906a8485", "module": "m1", "blocks": [{"id": "/source/m1::chto-govoryat-lyudi-s-invalidnostyu-i-nko::paragraph::pqnot", "kind": "paragraph", "snippet": "*Анастасия Плеханова, руководитель проекта “РИТМ”* [Благотворительный фонд «Действуй!»](ht…"}, {"id": "/source/m1::chto-govoryat-lyudi-s-invalidnostyu-i-nko::paragraph::1mfk43h", "kind": "quote", "snippet": "*Елена более десяти лет работала в маркетинге, а затем решила сменить профессию. Она получ…"}, {"id": "/source/m1::chto-govoryat-lyudi-s-invalidnostyu-i-nko::paragraph::17uwr7j", "kind": "quote", "snippet": "*У Елены инвалидность вследствие общего заболевания. Ей хотелось найти работу, которая соч…"}, {"id": "/source/m1::chto-govoryat-lyudi-s-invalidnostyu-i-nko::paragraph::181s82w", "kind": "quote", "snippet": "*Специалисты фонда помогли ей обновить резюме и начать активный поиск работы. За это время…"}], "target": "Quote", "targetLabel": "Quote — Анастасия Плеханова", "modifiers": {}, "comment": "История Елены от Анастасии Плехановой — в карточку цитаты, речь из трёх абзацев.\nПочему: Тот же случай: авторство отдельной строкой, а под ним три абзаца истории. Название фонда в строке авторства — ссылка, она и даёт организацию для карточки.", "status": "applied", "createdAt": "2026-08-07T09:24:02.620Z", "origin": "claude"},
  {"id": "b7ef6f30-2c5d-486d-a119-e233953d375c", "module": "m1", "blocks": [{"id": "/source/m1::kak-vystroit-ustoychivye-processy::h3::y48sh7", "kind": "heading", "snippet": "Итоговые рекомендации"}, {"id": "/source/m1::kak-vystroit-ustoychivye-processy::list::uwq41u", "kind": "list", "snippet": "1 пунктов"}, {"id": "/source/m1::kak-vystroit-ustoychivye-processy::list::safaxa", "kind": "list", "snippet": "1 пунктов"}, {"id": "/source/m1::kak-vystroit-ustoychivye-processy::list::2y8naj", "kind": "list", "snippet": "1 пунктов"}, {"id": "/source/m1::kak-vystroit-ustoychivye-processy::list::13krtwt", "kind": "list", "snippet": "1 пунктов"}, {"id": "/source/m1::kak-vystroit-ustoychivye-processy::list::gfx3gw", "kind": "list", "snippet": "1 пунктов"}], "target": "GeneralCard", "targetLabel": "General Card", "modifiers": {"orient": "Vertical", "bg": "blue", "icon": false, "step": false}, "comment": "Все в одну синюю карточку, заголовок «Итоговые рекомендации».\nПочему: Замечание клиента 7 августа 2026 («выделим как-то визуально?») и решение дизайнера («выделим в синюю карточку, этот заголовок и булиты под ним»). Пять советов подводят итог длинной странице, а стояли обычным списком среди таких же списков выше — глазом их было не отличить от очередного перечисления. В карточке итог виден сразу.", "status": "applied", "createdAt": "2026-08-07T14:31:16.490Z", "origin": "claude"},
]
